version: '2'
services:
  geography-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/geography/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=geography
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
